/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elwing.tictactoe;

import java.awt.*;
import java.awt.geom.Line2D;
import javax.swing.*;

/**
 *
 * @author Elwing
 */
enum DrawType {
    TypeNone,
    TypeCircle,
    TypeCross,
}    

public class TicTacToeUnitPanel extends javax.swing.JPanel {

    public DrawType drawType = DrawType.TypeNone;
    
    /**
     * Creates new form TicTacToeUnitPanel
     */
    public TicTacToeUnitPanel() {
        initComponents();
    }

    public void reset() {
        drawType = DrawType.TypeNone;
        removeAll();
        repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g) { 
        if(drawType == DrawType.TypeNone) {
            return;
        } else if (drawType == DrawType.TypeCircle) {
            drawCircle(g);
        } else if (drawType == DrawType.TypeCross) {
            drawCross(g);
        }
    } 
    
    private void drawCircle(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        int h = getHeight();
        int w = getWidth();
        super.paintComponent(g); 
        g2.setColor(Color.RED);
        g2.setStroke(new BasicStroke(3));
        g2.drawArc(0 + w/10 , 0 + h/10, w - w/5, h - h/5 ,0 , 360);    
    }
    
    private void drawCross(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        int h = getHeight();
        int w = getWidth();
        super.paintComponent(g); 
        g2.setColor(Color.BLUE);
        g2.setStroke(new BasicStroke(3));
        g2.drawLine(0 + w/10 , 0 + h/10, w - w/10, h - h/10);
        g2.drawLine(w - w/10 , 0 + h/10, 0 + w/10, h - h/10);    

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
