/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.elwing.tictactoe;

import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Elwing
 */
public class TicTacToeFrame extends javax.swing.JFrame implements MouseListener {

    private JPanel[] panelArray;
    /**
     * Creates new form TicTacToeFrame
     */
    TicTacToeBrain brain;
    public TicTacToeFrame() {
        brain = new TicTacToeBrain();
        initComponents();
        panelArray = new JPanel[9];
        panelArray[0] = unit_0;
        panelArray[1] = unit_1;
        panelArray[2] = unit_2;
        panelArray[3] = unit_3;
        panelArray[4] = unit_4;
        panelArray[5] = unit_5;
        panelArray[6] = unit_6;
        panelArray[7] = unit_7;
        panelArray[8] = unit_8;
        for (int i = 0; i < panelArray.length; i++) {
            panelArray[i].addMouseListener(this);
        }


    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
       TicTacToeUnitPanel source = (TicTacToeUnitPanel) e.getSource();
       source.removeMouseListener(this);
       String name = source.getName();
       int index = Integer.valueOf(name.split("_")[1]);
       int player = brain.fillTicTacToeAt(index);
       if(player == brain.playerCircle) {
           System.out.println("Circle is Pressed");
           source.drawType = DrawType.TypeCircle;
           source.repaint();
       } else if (player == brain.playerCross) {
           System.out.println("Cross is Pressed");
           source.drawType = DrawType.TypeCross;
           source.repaint();
       }
       
       int winner = brain.checkWinner();    
       if(winner != 0) {
           String winnerName = (winner == brain.playerCircle)?"Circle":"Cross";
           JOptionPane.showMessageDialog(this, winnerName + " won the game" );
           resetAll();
       }
    }
     
    @Override
    public void mousePressed(MouseEvent e) {
    }
     
    @Override
    public void mouseReleased(MouseEvent e) {
    }
     
    @Override
    public void mouseEntered(MouseEvent e) {
    }
     
    @Override
    public void mouseExited(MouseEvent e) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        unit_0 = new TicTacToeUnitPanel();
        unit_1 = new TicTacToeUnitPanel();
        unit_2 = new TicTacToeUnitPanel();
        unit_4 = new TicTacToeUnitPanel();
        unit_5 = new TicTacToeUnitPanel();
        unit_3 = new TicTacToeUnitPanel();
        unit_7 = new TicTacToeUnitPanel();
        unit_8 = new TicTacToeUnitPanel();
        unit_6 = new TicTacToeUnitPanel();
        resetButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("對戰紀錄");

        unit_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_0.setName("unit_0"); // NOI18N

        javax.swing.GroupLayout unit_0Layout = new javax.swing.GroupLayout(unit_0);
        unit_0.setLayout(unit_0Layout);
        unit_0Layout.setHorizontalGroup(
            unit_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_0Layout.setVerticalGroup(
            unit_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        unit_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_1.setName("unit_1"); // NOI18N

        javax.swing.GroupLayout unit_1Layout = new javax.swing.GroupLayout(unit_1);
        unit_1.setLayout(unit_1Layout);
        unit_1Layout.setHorizontalGroup(
            unit_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_1Layout.setVerticalGroup(
            unit_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        unit_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_2.setName("unit_2"); // NOI18N

        javax.swing.GroupLayout unit_2Layout = new javax.swing.GroupLayout(unit_2);
        unit_2.setLayout(unit_2Layout);
        unit_2Layout.setHorizontalGroup(
            unit_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_2Layout.setVerticalGroup(
            unit_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        unit_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_4.setName("unit_4"); // NOI18N

        javax.swing.GroupLayout unit_4Layout = new javax.swing.GroupLayout(unit_4);
        unit_4.setLayout(unit_4Layout);
        unit_4Layout.setHorizontalGroup(
            unit_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_4Layout.setVerticalGroup(
            unit_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        unit_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_5.setName("unit_5"); // NOI18N

        javax.swing.GroupLayout unit_5Layout = new javax.swing.GroupLayout(unit_5);
        unit_5.setLayout(unit_5Layout);
        unit_5Layout.setHorizontalGroup(
            unit_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_5Layout.setVerticalGroup(
            unit_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        unit_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_3.setName("unit_3"); // NOI18N

        javax.swing.GroupLayout unit_3Layout = new javax.swing.GroupLayout(unit_3);
        unit_3.setLayout(unit_3Layout);
        unit_3Layout.setHorizontalGroup(
            unit_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_3Layout.setVerticalGroup(
            unit_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        unit_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_7.setName("unit_7"); // NOI18N

        javax.swing.GroupLayout unit_7Layout = new javax.swing.GroupLayout(unit_7);
        unit_7.setLayout(unit_7Layout);
        unit_7Layout.setHorizontalGroup(
            unit_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_7Layout.setVerticalGroup(
            unit_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        unit_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_8.setName("unit_8"); // NOI18N

        javax.swing.GroupLayout unit_8Layout = new javax.swing.GroupLayout(unit_8);
        unit_8.setLayout(unit_8Layout);
        unit_8Layout.setHorizontalGroup(
            unit_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_8Layout.setVerticalGroup(
            unit_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        unit_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        unit_6.setName("unit_6"); // NOI18N

        javax.swing.GroupLayout unit_6Layout = new javax.swing.GroupLayout(unit_6);
        unit_6.setLayout(unit_6Layout);
        unit_6Layout.setHorizontalGroup(
            unit_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        unit_6Layout.setVerticalGroup(
            unit_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        resetButton.setText("開始下一場");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jButton2.setText("清除紀錄");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(unit_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(unit_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(unit_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(unit_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(unit_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(unit_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(unit_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(unit_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(unit_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unit_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unit_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unit_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("RESET!");
        resetAll();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void resetAll() {
        brain = new TicTacToeBrain();
        for(int i = 0; i < panelArray.length; i++) {
            TicTacToeUnitPanel unitPanel = (TicTacToeUnitPanel)panelArray[i];
            unitPanel.reset();
            unitPanel.removeMouseListener(this);
            unitPanel.addMouseListener(this);
        }
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TicTacToeFrame frame = new TicTacToeFrame();
                frame.setTitle("TicTacToe");
                frame.setResizable(false);
                frame.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetButton;
    private javax.swing.JPanel unit_0;
    private javax.swing.JPanel unit_1;
    private javax.swing.JPanel unit_2;
    private javax.swing.JPanel unit_3;
    private javax.swing.JPanel unit_4;
    private javax.swing.JPanel unit_5;
    private javax.swing.JPanel unit_6;
    private javax.swing.JPanel unit_7;
    private javax.swing.JPanel unit_8;
    // End of variables declaration//GEN-END:variables
}
